use tauri_specta::{collect_commands, Builder};

pub fn generate_bindings() -> Builder<tauri::Wry> {
    use crate::commands::{graph, notifications, preferences, recovery, timeseries};

    Builder::<tauri::Wry>::new().commands(collect_commands![
        graph::load_graph,
        graph::compute_centrality,
        preferences::greet,
        preferences::load_preferences,
        preferences::save_preferences,
        notifications::send_native_notification,
        recovery::save_emergency_data,
        recovery::load_emergency_data,
        recovery::cleanup_old_recovery_files,
        timeseries::load_timeseries,
        timeseries::save_timeseries,
        timeseries::add_timeseries_point,
        timeseries::query_timeseries_range,
        timeseries::get_timeseries_ids,
        timeseries::clear_timeseries,
    ])
}

/// Export TypeScript bindings to the frontend.
/// Run with: cargo test export_bindings -- --ignored
pub fn export_ts_bindings() {
    generate_bindings()
        .export(
            specta_typescript::Typescript::default()
                .header("// @ts-nocheck\n// Auto-generated by tauri-specta. DO NOT EDIT.\n\n"),
            "../src/lib/bindings.ts",
        )
        .expect("Failed to export TypeScript bindings");
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Generate TypeScript bindings file.
    /// This test is ignored by default so it doesn't run in CI.
    /// Run manually with: cargo test export_bindings -- --ignored
    #[test]
    #[ignore]
    fn export_bindings() {
        export_ts_bindings();
        println!("✓ TypeScript bindings exported to ../src/lib/bindings.ts");
    }
}
